#!/usr/bin/env bash
# Interactive release-signing setup for a Flutter Android app.
#
# Usage: bash setup_signing.sh <app-root> [--keys-dir <dir>]
#
# Generates an *upload* keystore (never the Play app-signing key) and writes
# <app-root>/android/key.properties. Passwords are prompted for and never leave the terminal.
# Existing key.properties and existing keystores are never overwritten.
#
# Intended layout (keystore outside the repo):
#   <app-root>/android/key.properties          -> storeFile=../../.keys/<app>/upload-keystore.jks
#
# After running: enable Play App Signing in Play Console and keep an offline backup of the upload key.

set -uo pipefail

APP_ROOT="${1:-}"
KEYS_DIR=""
shift || true
while [ $# -gt 0 ]; do
  case "$1" in
    --keys-dir) KEYS_DIR="${2:-}"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -z "$APP_ROOT" ] || [ ! -f "$APP_ROOT/pubspec.yaml" ]; then
  echo "usage: bash setup_signing.sh <app-root> [--keys-dir <dir>]" >&2
  exit 2
fi
cd "$APP_ROOT" || exit 2

command -v keytool >/dev/null 2>&1 || { echo "keytool not found: install a JDK (Android Studio JBR is fine)" >&2; exit 1; }

APP_NAME="$(basename "$(pwd)")"
[ -n "$KEYS_DIR" ] || KEYS_DIR="$(cd .. && pwd)/.keys/$APP_NAME"
KS_NAME="upload-keystore.jks"
KEYSTORE="$KEYS_DIR/$KS_NAME"
PROPS="android/key.properties"

if [ -f "$PROPS" ]; then
  echo "android/key.properties already exists - nothing to do."
  exit 0
fi
if [ -f "$KEYSTORE" ]; then
  echo "keystore already exists at $KEYSTORE but key.properties does not."
  echo "Recover the passwords and write $PROPS by hand:"
  echo "  storePassword=...\n  keyPassword=...\n  keyAlias=upload\n  storeFile=$KEYSTORE"
  exit 1
fi

echo "Upload-key setup for $APP_NAME"
echo "keystore will be written OUTSIDE the repo: $KEYSTORE"
echo
read -r -p "Key alias [upload]: " ALIAS
ALIAS="${ALIAS:-upload}"
read -r -p "Alias password (input hidden): " KEY_PASS
[ -n "$KEY_PASS" ] || { echo "password required" >&2; exit 1; }
read -r -p "Key password (input hidden, Enter = same as alias password): " KEY_PASS2
[ -n "$KEY_PASS2" ] || KEY_PASS2="$KEY_PASS"
read -r -p "Store password (input hidden, Enter = same as alias password): " STORE_PASS
[ -n "$STORE_PASS" ] || STORE_PASS="$KEY_PASS"
read -r -p "Validity in days [10000]: " VALIDITY
VALIDITY="${VALIDITY:-10000}"

mkdir -p "$KEYS_DIR" || exit 1
chmod 700 "$KEYS_DIR"

keytool -genkeypair -v \
  -keystore "$KEYSTORE" \
  -storetype JKS \
  -keyalg RSA -keysize 4096 \
  -validity "$VALIDITY" \
  -alias "$ALIAS" \
  -storepass "$STORE_PASS" \
  -keypass "$KEY_PASS" \
  -dname "CN=$APP_NAME, OU=Appnovasi, O=Appnovasi, L=Jakarta, C=ID" || {
  echo "keytool failed" >&2
  exit 1
}

# Gradle resolves storeFile through rootProject.file(), i.e. relative to the android/ directory.
ABS_ANDROID="$(cd android && pwd)"
if command -v python3 >/dev/null 2>&1; then
  REL_STORE="$(python3 -c 'import os,sys;print(os.path.relpath(sys.argv[1], sys.argv[2]))' "$KEYSTORE" "$ABS_ANDROID")"
else
  REL_STORE="$KEYSTORE"
fi

cat > "$PROPS" <<EOF
# Generated by .opencode/skills/store-release/scripts/setup_signing.sh
# NEVER COMMIT. Back up this keystore: without it you cannot upload app updates.
storePassword=$STORE_PASS
keyPassword=$KEY_PASS2
keyAlias=$ALIAS
storeFile=$REL_STORE
EOF

chmod 600 "$PROPS"
echo
echo "wrote $PROPS"
echo "keystore: $KEYSTORE"

# fail loudly instead of committing secrets
GIT_ROOT="$(git rev-parse --show-toplevel 2>/dev/null)"
if [ -n "$GIT_ROOT" ]; then
  for pattern in "**/key.properties" "**/*.jks" "**/*.keystore"; do
    if ! grep -qxF "$pattern" "$GIT_ROOT/.gitignore" 2>/dev/null; then
      printf '%s\n' "$pattern" >> "$GIT_ROOT/.gitignore"
      echo "added $pattern to $GIT_ROOT/.gitignore"
    fi
  done
  if git -C "$GIT_ROOT" check-ignore -q "$PROPS" 2>/dev/null; then
    echo "ok: $PROPS is git-ignored"
  else
    echo "WARNING: $PROPS is NOT git-ignored, fix .gitignore before committing"
  fi
fi

echo
echo "Next:"
echo "  1. apply the signing + R8 patch from references/native-release-setup.md"
echo "  2. flutter build appbundle --release"
echo "  3. enable Play App Signing in Play Console -> App integrity -> App signing"
echo "  4. back up $KEYSTORE offline"